#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe PostaController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # Postum. As you add validations to Postum, be sure to
#  # adjust the attributes here as well.
#  let(:valid_attributes) { { "body" => "MyString" } }
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # PostaController. Be sure to keep this updated too.
#  let(:valid_session) { {} }
#
#  describe "GET index" do
#    it "assigns all posta as @posta" do
#      postum = Postum.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:posta).should eq([postum])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested postum as @postum" do
#      postum = Postum.create! valid_attributes
#      get :show, {:id => postum.to_param}, valid_session
#      assigns(:postum).should eq(postum)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new postum as @postum" do
#      get :new, {}, valid_session
#      assigns(:postum).should be_a_new(Postum)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested postum as @postum" do
#      postum = Postum.create! valid_attributes
#      get :edit, {:id => postum.to_param}, valid_session
#      assigns(:postum).should eq(postum)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new Postum" do
#        expect {
#          post :create, {:postum => valid_attributes}, valid_session
#        }.to change(Postum, :count).by(1)
#      end
#
#      it "assigns a newly created postum as @postum" do
#        post :create, {:postum => valid_attributes}, valid_session
#        assigns(:postum).should be_a(Postum)
#        assigns(:postum).should be_persisted
#      end
#
#      it "redirects to the created postum" do
#        post :create, {:postum => valid_attributes}, valid_session
#        response.should redirect_to(Postum.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved postum as @postum" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Postum.any_instance.stub(:save).and_return(false)
#        post :create, {:postum => { "body" => "invalid value" }}, valid_session
#        assigns(:postum).should be_a_new(Postum)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Postum.any_instance.stub(:save).and_return(false)
#        post :create, {:postum => { "body" => "invalid value" }}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested postum" do
#        postum = Postum.create! valid_attributes
#        # Assuming there are no other posta in the database, this
#        # specifies that the Postum created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        Postum.any_instance.should_receive(:update_attributes).with({ "body" => "MyString" })
#        put :update, {:id => postum.to_param, :postum => { "body" => "MyString" }}, valid_session
#      end
#
#      it "assigns the requested postum as @postum" do
#        postum = Postum.create! valid_attributes
#        put :update, {:id => postum.to_param, :postum => valid_attributes}, valid_session
#        assigns(:postum).should eq(postum)
#      end
#
#      it "redirects to the postum" do
#        postum = Postum.create! valid_attributes
#        put :update, {:id => postum.to_param, :postum => valid_attributes}, valid_session
#        response.should redirect_to(postum)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the postum as @postum" do
#        postum = Postum.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Postum.any_instance.stub(:save).and_return(false)
#        put :update, {:id => postum.to_param, :postum => { "body" => "invalid value" }}, valid_session
#        assigns(:postum).should eq(postum)
#      end
#
#      it "re-renders the 'edit' template" do
#        postum = Postum.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Postum.any_instance.stub(:save).and_return(false)
#        put :update, {:id => postum.to_param, :postum => { "body" => "invalid value" }}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested postum" do
#      postum = Postum.create! valid_attributes
#      expect {
#        delete :destroy, {:id => postum.to_param}, valid_session
#      }.to change(Postum, :count).by(-1)
#    end
#
#    it "redirects to the posta list" do
#      postum = Postum.create! valid_attributes
#      delete :destroy, {:id => postum.to_param}, valid_session
#      response.should redirect_to(posta_url)
#    end
#  end
#
#end
